# site_name: My Docs

# theme:
#   name: material

#   logo: assets/logo.png

#   palette:
#     # automatic mode
#     - media: "(prefers-color-scheme)"
#       toggle:
#         icon: material/toggle-auto
#         name: Modo noturno

#     # light mode
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       toggle:
#         icon: material/toggle-switch
#         name: Modo noturno
    
#     # dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       toggle:
#         icon: material/toggle-switch-off-outline
#         name: Modo dia

# extra_css:
#   - stylesheets/extra.css

site_name: Venci na Promo
site_author: Grupo GPT - 2023.1 - Requisitos de Software - FGA - UnB
copyright: |
  &copy; 2023.1 <a href="https://mdsreq-fga-unb.github.io/2023.1-VenciNaPromo.git"  target="_blank" rel="noopener">Grupo GPT - 2023.1 - Requisitos de Software - FGA - UnB</a>


theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: indigo
      

nav:
  - Início: "index.md"   
  - Documentação:
    - Visão do Produto e Projeto: "projeto/visao.md" 

repo_url: https://mdsreq-fga-unb.github.io/2023.1-VenciNaPromo
repo_name: mdsreq-fga-unb.github.io/2023.1-VenciNaPromo
 
 
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences

