docs_dir: "ghpages/docs"
site_name: Venci na Promo
site_author: Grupo GPT - 2023.1 - Requisitos de Software - FGA - UnB
copyright: |
  &copy; 2023.1 <a href="https://mdsreq-fga-unb.github.io/2023.1-VenciNaPromo.git"  target="_blank" rel="noopener">Grupo GPT - 2023.1 - Requisitos de Software - FGA - UnB</a>

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/git-alt
  # logo: "icon-640.png"
  # favicon: "favicon-640.png"
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: deep orange
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep orange
      accent: indigo

nav:
  - Início: "index.md"
  - Documentação:
      - Visão do Produto e Projeto: "projeto/visao.md"
      - Processo de Engenharia de Requisitos: "projeto/processoER.md"
      - Backlog do Produto: "projeto/backlog.md"
      - Definição dos MVP's: "projeto/mvp.md"
      - URPS+: "projeto/nao-fun.md"
      - Protótipo do MVP 1: "projeto/prototipoMVP1.md"
      - Backlog SAFe: "projeto/SAFe.md"
      - BDD: "projeto/BDD.md"
      - PBB: "projeto/PBB.md"
      - USM: "projeto/USM.md"
      - Casos de Uso: "projeto/casosDeUso.md"
  - Entregas:
      - Unidade 1:
          - Visão Geral do Produto: "entregas/produto-entrega-1.md"
          - Material do Seminário XP: "entregas/seminario-1.md"
      - Unidade 2: "entregas/unidade-2.md"
      - Unidade 3: 
          - Apresentação para o Cliente: "entregas/apresentacao-cliente-3.md"
          - Apresentação Equipe: "entregas/apresentacao-3"
      - Unidade 4:
          - Apresentação para o Cliente: "entregas/apresentacao-cliente-4.md"
          - Apresentação Equipe: "entregas/apresentacao-4"
  - Sprints:
      - Sprint 1: "sprints/sprint1.md"
      - Sprint 2: "sprints/sprint2.md"
      - Sprint 3: "sprints/sprint3.md"
      - Sprint 4: "sprints/sprint4.md"
      - Sprint 5: "sprints/sprint5.md"
      - Sprint 6: "sprints/sprint6.md"
      - Sprint 7: "sprints/sprint7.md"
      - Sprint 8: "sprints/sprint8.md"
      - Sprint 9: "sprints/sprint9.md"
      - Sprint 10: "sprints/sprint10.md"
      - Sprint 11: "sprints/sprint11.md"
      - Sprint 12: "sprints/sprint12.md"
      - Sprint 13: "sprints/sprint13.md"

repo_url: https://github.com/mdsreq-fga-unb/2023.1-VenciNaPromo
repo_name: mdsreq-fga-unb.github.io/2023.1-VenciNaPromo

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
